version: '3.8'

services:
  flaskapp:
    image: mvasquezb999/bookstore-scalable
    restart: always
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - /mnt/shared:/app/uploads