version: '3.8'

services:
  flaskapp:
    build: mvasquezb999/bookstore-scalable
    restart: always
    environment:
      - FLASK_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - /mnt/shared:/app/uploads